>>> 'Pkg.add("CauseMap")' log
INFO: Cloning cache of CauseMap from git://github.com/cyrusmaher/CauseMap.jl.git
INFO: Cloning cache of Dates from git://github.com/quinnj/Dates.jl.git
INFO: Cloning cache of PyCall from git://github.com/stevengj/PyCall.jl.git
INFO: Installing CauseMap v0.0.2
INFO: Installing Compat v0.2.5
INFO: Installing Dates v0.3.2
INFO: Installing PyCall v0.7.3
INFO: Package database updated

>>> 'using CauseMap' log
Julia Version 0.3.1
Commit c03f413* (2014-09-21 21:30 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

>>> test log
Starting bootstrap test

ERROR: PyError (:PyImport_ImportModule) <class 'ImportError'>
ImportError("No module named 'matplotlib'",)

 in pyerr_check at /home/idunning/pkgtest/.julia/v0.3/PyCall/src/exception.jl:58
 in pyimport at /home/idunning/pkgtest/.julia/v0.3/PyCall/src/PyCall.jl:91
 in makesingleplot at /home/idunning/pkgtest/.julia/v0.3/CauseMap/src/plotting.jl:372
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_1712 at /home/idunning/julia03/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.3/CauseMap/test/testplotting.jl, in expression starting on line 15
while loading /home/idunning/pkgtest/.julia/v0.3/CauseMap/test/runtests.jl, in expression starting on line 1
INFO: Testing CauseMap
==============================[ ERROR: CauseMap ]===============================

failed process: Process(`/home/idunning/julia03/usr/bin/julia /home/idunning/pkgtest/.julia/v0.3/CauseMap/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: CauseMap had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:715
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:67
 in process_options at ./client.jl:213
 in _start at ./client.jl:354
 in _start_3B_1712 at /home/idunning/julia03/usr/bin/../lib/julia/sys.so


>>> end of log
