>>> 'Pkg.add("EllipticFEM")' log
INFO: Cloning cache of EllipticFEM from https://github.com/gerhardtulzer/EllipticFEM.jl.git
INFO: Installing BinDeps v0.6.0
INFO: Installing ColorTypes v0.5.1
INFO: Installing Colors v0.7.3
INFO: Installing Conda v0.5.3
INFO: Installing DataStructures v0.6.0
INFO: Installing EllipticFEM v0.0.2
INFO: Installing FixedPointNumbers v0.3.8
INFO: Installing GZip v0.3.0
INFO: Installing LaTeXStrings v0.2.1
INFO: Installing LightGraphs v0.9.1
INFO: Installing MacroTools v0.3.7
INFO: Installing PyCall v1.14.0
INFO: Installing PyPlot v2.3.2
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.3.3
INFO: Installing SimpleTraits v0.5.0
INFO: Installing URIParser v0.1.8
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").

CondaHTTPError: HTTP 504 GATEWAY TIME-OUT for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: 02:00.293848
CF-RAY: 37d5fe90e8ab5a44-BOS

An remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.


===============================[ ERROR: PyCall ]================================

LoadError: failed process: Process(setenv(`/home/vagrant/.julia/v0.6/Conda/deps/usr/bin/conda install -y numpy`,String["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/", "PWD=/vagrant/0.6AK", "SHELL=/bin/bash", "SSH_CONNECTION=10.0.2.2 49799 10.0.2.15 22", "LD_LIBRARY_PATH=:/usr/local/lib/", "CONDARC=/home/vagrant/.julia/v0.6/Conda/deps/usr/condarc-julia.yml", "MAIL=/var/mail/vagrant", "LANG=en_US.UTF-8", "SHLVL=3", "LOGNAME=vagrant", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SESSION_ID=3", "CONDA_PREFIX=/home/vagrant/.julia/v0.6/Conda/deps/usr", "OLDPWD=/home/vagrant", "SSH_CLIENT=10.0.2.2 49799 22", "_=/usr/bin/timeout", "CONDA_DEFAULT_ENV=/home/vagrant/.julia/v0.6/Conda/deps/usr", "USER=vagrant", "TERM=vt100", "HOME=/home/vagrant", "OPENBLAS_MAIN_FREE=1", "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"]), ProcessExited(1)) [1]
while loading /home/vagrant/.julia/v0.6/PyCall/deps/build.jl, in expression starting on line 258

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/vagrant/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of EllipticFEM
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("EllipticFEM")' log
Julia Version 0.6.0
Commit 9036443 (2017-06-19 13:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-121-generic #170-Ubuntu SMP Wed Jun 14 09:04:33 UTC 2017 x86_64 x86_64
Memory: 2.9392738342285156 GB (754.25 MB free)
Uptime: 50096.0 sec
Load Avg:  0.20458984375  0.6845703125  0.84912109375
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3500 MHz    3129474 s       5585 s     146354 s     957936 s         20 s
#2  3500 MHz     867808 s         42 s      96380 s    3918931 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.6
2 required packages:
 - EllipticFEM                   0.0.2
 - JSON                          0.12.0
17 additional packages:
 - BinDeps                       0.6.0
 - ColorTypes                    0.5.1
 - Colors                        0.7.3
 - Compat                        0.26.0
 - Conda                         0.5.3
 - DataStructures                0.6.0
 - FixedPointNumbers             0.3.8
 - GZip                          0.3.0
 - LaTeXStrings                  0.2.1
 - LightGraphs                   0.9.1
 - MacroTools                    0.3.7
 - PyCall                        1.14.0
 - PyPlot                        2.3.2
 - Reexport                      0.0.3
 - SHA                           0.3.3
 - SimpleTraits                  0.5.0
 - URIParser                     0.1.8
INFO: Testing EllipticFEM
ERROR: LoadError: LoadError: PyCall not properly installed. Please run Pkg.build("PyCall")
Stacktrace:
 [1] macro expansion at /home/vagrant/.julia/v0.6/PyCall/src/startup.jl:45 [inlined]
 [2] anonymous at ./<missing>:?
 [3] include_from_node1(::String) at ./loading.jl:569
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:569
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /home/vagrant/.julia/v0.6/PyCall/src/startup.jl, in expression starting on line 42
while loading /home/vagrant/.julia/v0.6/PyCall/src/PyCall.jl, in expression starting on line 39
ERROR: LoadError: LoadError: Failed to precompile PyCall to /home/vagrant/.julia/lib/v0.6/PyCall.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:456
 [3] require(::Symbol) at ./loading.jl:398
 [4] _include_from_serialized(::String) at ./loading.jl:157
 [5] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:200
 [6] _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:236
 [7] _require(::Symbol) at ./loading.jl:434
 [8] require(::Symbol) at ./loading.jl:398
 [9] include_from_node1(::String) at ./loading.jl:569
while loading /home/vagrant/.julia/v0.6/EllipticFEM/src/EllipticFEM.jl, in expression starting on line 3
while loading /home/vagrant/.julia/v0.6/EllipticFEM/test/runtests.jl, in expression starting on line 2
=============================[ ERROR: EllipticFEM ]=============================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/EllipticFEM/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: EllipticFEM had test errors

>>> End of log
