>>> 'Pkg.add("IPython")' log
INFO: Cloning cache of IPython from https://github.com/tkf/IPython.jl.git
INFO: Installing BinDeps v0.8.8
INFO: Installing Conda v0.7.1
INFO: Installing IPython v0.0.1
INFO: Installing MacroTools v0.4.0
INFO: Installing PyCall v1.16.1
INFO: Installing SHA v0.5.7
INFO: Installing URIParser v0.3.1
INFO: Installing VersionParsing v1.1.0
INFO: Building Conda
INFO: Building PyCall
Info: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Solving environment: ...working... done

# All requested packages already installed.

Info: PyCall is using /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python (Python 2.7.14) at /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.6/Conda/deps/usr/lib/libpython2.7
Info: /home/vagrant/.julia/v0.6/PyCall/deps/deps.jl has not changed
Info: /home/vagrant/.julia/v0.6/PyCall/deps/PYTHON has not changed
INFO: Package database updated

>>> 'Pkg.test("IPython")' log
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64
Memory: 2.939197540283203 GB (1554.6953125 MB free)
Uptime: 37148.0 sec
Load Avg:  0.9970703125  0.9853515625  0.955078125
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3504 MHz    2159640 s       1381 s     170074 s     851752 s         29 s
#2  3504 MHz     445837 s       5622 s      65563 s    3127735 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.6
2 required packages:
 - IPython                       0.0.1
 - JSON                          0.17.2
9 additional packages:
 - BinDeps                       0.8.8
 - Compat                        0.64.0
 - Conda                         0.7.1
 - MacroTools                    0.4.0
 - Nullables                     0.0.5
 - PyCall                        1.16.1
 - SHA                           0.5.7
 - URIParser                     0.3.1
 - VersionParsing                1.1.0
INFO: Testing IPython
PyCall.pyprogramname = "/home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python"
PyCall.pyversion = v"2.7.14"
PyCall.libpython = "/home/vagrant/.julia/v0.6/Conda/deps/usr/lib/libpython2.7"
PyCall.conda = true
ERROR: LoadError: PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, kw)) <type 'exceptions.ImportError'>
ImportError('No module named julia',)
  File "/home/vagrant/.julia/v0.6/IPython/src/replhelper.py", line 33, in ipython_options
    from julia import Julia

Stacktrace:
 [1] pyerr_check at /home/vagrant/.julia/v0.6/PyCall/src/exception.jl:58 [inlined]
 [2] pyerr_check at /home/vagrant/.julia/v0.6/PyCall/src/exception.jl:62 [inlined]
 [3] macro expansion at /home/vagrant/.julia/v0.6/PyCall/src/exception.jl:82 [inlined]
 [4] #_pycall#88(::Array{Any,1}, ::Function, ::PyCall.PyObject) at /home/vagrant/.julia/v0.6/PyCall/src/PyCall.jl:715
 [5] (::PyCall.#kw##_pycall)(::Array{Any,1}, ::PyCall.#_pycall, ::PyCall.PyObject) at ./<missing>:0
 [6] #pycall#92(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}) at /home/vagrant/.julia/v0.6/PyCall/src/PyCall.jl:732
 [7] (::PyCall.#kw##pycall)(::Array{Any,1}, ::PyCall.#pycall, ::PyCall.PyObject, ::Type{PyCall.PyAny}) at ./<missing>:0
 [8] #call#93 at /home/vagrant/.julia/v0.6/PyCall/src/PyCall.jl:735 [inlined]
 [9] (::PyCall.#kw#PyObject)(::Array{Any,1}, ::PyCall.PyObject) at ./<missing>:0
 [10] #_start_ipython#1(::Array{Any,1}, ::Function, ::Symbol) at /home/vagrant/.julia/v0.6/IPython/src/IPython.jl:7
 [11] _start_ipython(::Symbol) at /home/vagrant/.julia/v0.6/IPython/src/IPython.jl:7
 [12] include_from_node1(::String) at ./loading.jl:576
 [13] include(::String) at ./sysimg.jl:14
 [14] process_options(::Base.JLOptions) at ./client.jl:305
 [15] _start() at ./client.jl:371
while loading /home/vagrant/.julia/v0.6/IPython/test/runtests.jl, in expression starting on line 237
===============================[ ERROR: IPython ]===============================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/IPython/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: IPython had test errors

>>> End of log
