>>> 'Pkg.add("PlyIO")' log
INFO: Cloning cache of PlyIO from https://github.com/FugroRoames/PlyIO.jl.git
INFO: Installing PlyIO v0.0.2
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of PlyIO
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("PlyIO")' log
Julia Version 0.6.0-pre.beta.127
Commit 94417e4 (2017-04-13 19:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-116-generic #163-Ubuntu SMP Fri Mar 31 14:13:22 UTC 2017 x86_64 x86_64
Memory: 2.9392738342285156 GB (1074.8828125 MB free)
Uptime: 36940.0 sec
Load Avg:  0.90234375  0.98193359375  0.9609375
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3500 MHz    2439244 s        108 s     105515 s     563580 s         51 s
#2  3500 MHz     495531 s       6175 s      55415 s    3077420 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.6
2 required packages:
 - JSON                          0.9.0
 - PlyIO                         0.0.2
1 additional packages:
 - Compat                        0.23.0
INFO: Computing test dependencies for PlyIO...
INFO: Installing StaticArrays v0.4.0
INFO: Testing PlyIO

WARNING: deprecated syntax "typealias PropNameList Union{AbstractVector,Tuple}" at /home/vagrant/.julia/v0.6/PlyIO/src/types.jl:13.
Use "const PropNameList = Union{AbstractVector,Tuple}" instead.
WARNING: Base.linearindexing is deprecated, use Base.IndexStyle instead.
  likely near /home/vagrant/.julia/v0.6/PlyIO/src/types.jl:44
WARNING: Base.linearindexing is deprecated, use Base.IndexStyle instead.
  likely near /home/vagrant/.julia/v0.6/PlyIO/src/types.jl:83

WARNING: deprecated syntax "typealias PlyNativeType Union{UInt8,UInt16,UInt32,UInt64,Int8,Int16,Int32,Int64,Float32,Float64}" at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:48.
Use "const PlyNativeType = Union{UInt8,UInt16,UInt32,UInt64,Int8,Int16,Int32,Int64,Float32,Float64}" instead.
WARNING: takebuf_string(b) is deprecated, use String(take!(b)) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] takebuf_string(::Base.AbstractIOBuffer{Array{UInt8,1}}) at ./deprecated.jl:51
 [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:25 [inlined]
 [4] macro expansion at ./test.jl:853 [inlined]
 [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
 [6] macro expansion at ./test.jl:853 [inlined]
 [7] anonymous at ./<missing>:?
 [8] include_from_node1(::String) at ./loading.jl:539
 [9] include(::String) at ./sysimg.jl:14
 [10] process_options(::Base.JLOptions) at ./client.jl:305
 [11] _start() at ./client.jl:371
while loading /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl, in expression starting on line 5
WARNING: takebuf_string(b) is deprecated, use String(take!(b)) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] takebuf_string(::Base.AbstractIOBuffer{Array{UInt8,1}}) at ./deprecated.jl:51
 [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:61 [inlined]
 [4] macro expansion at ./test.jl:853 [inlined]
 [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
 [6] macro expansion at ./test.jl:853 [inlined]
 [7] anonymous at ./<missing>:?
 [8] include_from_node1(::String) at ./loading.jl:539
 [9] include(::String) at ./sysimg.jl:14
 [10] process_options(::Base.JLOptions) at ./client.jl:305
 [11] _start() at ./client.jl:371
while loading /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl, in expression starting on line 5
ascii=false: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::IOStream) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::IOStream) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] open(::PlyIO.##15#16, ::String, ::String) at ./iostream.jl:152
   [4] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:103 [inlined]
   [5] macro expansion at ./test.jl:914 [inlined]
   [6] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [7] macro expansion at ./test.jl:853 [inlined]
   [8] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [9] macro expansion at ./test.jl:853 [inlined]
   [10] anonymous at ./<missing>:?
   [11] include_from_node1(::String) at ./loading.jl:539
   [12] include(::String) at ./sysimg.jl:14
   [13] process_options(::Base.JLOptions) at ./client.jl:305
   [14] _start() at ./client.jl:371
ascii=true: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::IOStream) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::IOStream) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] open(::PlyIO.##15#16, ::String, ::String) at ./iostream.jl:152
   [4] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:103 [inlined]
   [5] macro expansion at ./test.jl:914 [inlined]
   [6] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [7] macro expansion at ./test.jl:853 [inlined]
   [8] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [9] macro expansion at ./test.jl:853 [inlined]
   [10] anonymous at ./<missing>:?
   [11] include_from_node1(::String) at ./loading.jl:539
   [12] include(::String) at ./sysimg.jl:14
   [13] process_options(::Base.JLOptions) at ./client.jl:305
   [14] _start() at ./client.jl:371
proptype=Int8: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
proptype=Int16: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
proptype=Int32: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
proptype=Int64: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
proptype=UInt8: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
proptype=UInt16: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
proptype=UInt32: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
proptype=UInt64: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
proptype=Float32: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
proptype=Float64: Error During Test
  Got an exception of type AssertionError outside of a @test
  AssertionError: readline(ply_file) == "ply\n"
  Stacktrace:
   [1] read_header(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:59
   [2] load_ply(::Base.AbstractIOBuffer{Array{UInt8,1}}) at /home/vagrant/.julia/v0.6/PlyIO/src/io.jl:301
   [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:124 [inlined]
   [4] macro expansion at ./test.jl:914 [inlined]
   [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [6] macro expansion at ./test.jl:853 [inlined]
   [7] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
   [8] macro expansion at ./test.jl:853 [inlined]
   [9] anonymous at ./<missing>:?
   [10] include_from_node1(::String) at ./loading.jl:539
   [11] include(::String) at ./sysimg.jl:14
   [12] process_options(::Base.JLOptions) at ./client.jl:305
   [13] _start() at ./client.jl:371
WARNING: takebuf_string(b) is deprecated, use String(take!(b)) instead.
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] takebuf_string(::Base.AbstractIOBuffer{Array{UInt8,1}}) at ./deprecated.jl:51
 [3] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:144 [inlined]
 [4] macro expansion at ./test.jl:853 [inlined]
 [5] macro expansion at /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl:0 [inlined]
 [6] macro expansion at ./test.jl:853 [inlined]
 [7] anonymous at ./<missing>:?
 [8] include_from_node1(::String) at ./loading.jl:539
 [9] include(::String) at ./sysimg.jl:14
 [10] process_options(::Base.JLOptions) at ./client.jl:305
 [11] _start() at ./client.jl:371
while loading /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl, in expression starting on line 5
Test Summary:        | Pass  Error  Total
PlyIO                |    3     12     15
  simple             |    1             1
  empty elements     |    1             1
  roundtrip          |          12     12
    ascii=false      |           1      1
    ascii=true       |           1      1
    proptype=Int8    |           1      1
    proptype=Int16   |           1      1
    proptype=Int32   |           1      1
    proptype=Int64   |           1      1
    proptype=UInt8   |           1      1
    proptype=UInt16  |           1      1
    proptype=UInt32  |           1      1
    proptype=UInt64  |           1      1
    proptype=Float32 |           1      1
    proptype=Float64 |           1      1
  SVector properties |    1             1
ERROR: LoadError: Some tests did not pass: 3 passed, 0 failed, 12 errored, 0 broken.
while loading /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl, in expression starting on line 5
================================[ ERROR: PlyIO ]================================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/PlyIO/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: Removing StaticArrays v0.4.0
ERROR: PlyIO had test errors

>>> End of log
