>>> 'Pkg.add("PyAMG")' log
INFO: Installing BinDeps v0.6.0
INFO: Installing Conda v0.5.3
INFO: Installing MacroTools v0.3.7
INFO: Installing PyAMG v0.1.1
INFO: Installing PyCall v1.13.0
INFO: Installing SHA v0.3.3
INFO: Installing URIParser v0.1.8
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.5/Conda/deps/usr:
#
numpy                     1.13.0                   py27_0  
INFO: PyCall is using /home/vagrant/.julia/v0.5/Conda/deps/usr/bin/python (Python 2.7.13) at /home/vagrant/.julia/v0.5/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.5/Conda/deps/usr/lib/libpython2.7
INFO: /home/vagrant/.julia/v0.5/PyCall/deps/deps.jl has not changed
INFO: /home/vagrant/.julia/v0.5/PyCall/deps/PYTHON has not changed
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of PyAMG
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("PyAMG")' log
Julia Version 0.5.2
Commit f4c6c9d (2017-05-06 16:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-121-generic #170-Ubuntu SMP Wed Jun 14 09:04:33 UTC 2017 x86_64 x86_64
Memory: 2.9392738342285156 GB (660.8671875 MB free)
Uptime: 26131.0 sec
Load Avg:  1.13232421875  1.0546875  0.9765625
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3510 MHz    1575500 s       6561 s     154620 s     565104 s         50 s
#2  3510 MHz     460944 s         93 s      72204 s    2017976 s          1 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.5
2 required packages:
 - JSON                          0.12.0
 - PyAMG                         0.1.1
7 additional packages:
 - BinDeps                       0.6.0
 - Compat                        0.26.0
 - Conda                         0.5.3
 - MacroTools                    0.3.7
 - PyCall                        1.13.0
 - SHA                           0.3.3
 - URIParser                     0.1.8
INFO: Computing test dependencies for PyAMG...
INFO: Installing DataStructures v0.5.3
INFO: Installing IterativeSolvers v0.3.1
INFO: Installing LinearMaps v0.3.0
INFO: Installing RecipesBase v0.1.0
INFO: Installing SpecialFunctions v0.1.1
INFO: Installing StatsBase v0.16.0
INFO: Installing SugarBLAS v0.0.3
INFO: Installing UnicodePlots v0.2.4
INFO: Testing PyAMG
=================================================
Test 1: Julia `\` vs PyAMG Blackbox `solve` (2D) Laplacian
 \ :   1.195552 seconds (553.79 k allocations: 32.026 MB, 7.93% gc time)
PyAMG-Warmup: /home/vagrant/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/pyamg/strength.py:533: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if B == 'ones':
ERROR: LoadError: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError('Failed generating smoothed_aggregation_solver',)
  File "/home/vagrant/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/pyamg/blackbox.py", line 284, in solve
    existing_solver = solver(A, config)
  File "/home/vagrant/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/pyamg/blackbox.py", line 215, in solver
    raise TypeError('Failed generating smoothed_aggregation_solver')

 in pyerr_check at /home/vagrant/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /home/vagrant/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /home/vagrant/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in #_pycall#66(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::PyCall.PyObject, ::Vararg{Any,N}) at /home/vagrant/.julia/v0.5/PyCall/src/PyCall.jl:625
 in (::PyCall.#kw##_pycall)(::Array{Any,1}, ::PyCall.#_pycall, ::PyCall.PyObject, ::PyCall.PyObject, ::Vararg{Any,N}) at ./<missing>:0
 in #pycall#70(::Array{Any,1}, ::Function, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::PyCall.PyObject, ::Vararg{Any,N}) at /home/vagrant/.julia/v0.5/PyCall/src/PyCall.jl:642
 in (::PyCall.#kw##pycall)(::Array{Any,1}, ::PyCall.#pycall, ::PyCall.PyObject, ::Type{PyCall.PyAny}, ::PyCall.PyObject, ::Vararg{Any,N}) at ./<missing>:0
 in #call#71(::Array{Any,1}, ::PyCall.PyObject, ::PyCall.PyObject, ::Vararg{Any,N}) at /home/vagrant/.julia/v0.5/PyCall/src/PyCall.jl:645
 in (::PyCall.#kw#PyObject)(::Array{Any,1}, ::PyCall.PyObject, ::PyCall.PyObject, ::Vararg{Any,N}) at ./<missing>:0
 in #solve#4(::Array{Any,1}, ::Function, ::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}) at /home/vagrant/.julia/v0.5/PyAMG/src/PyAMG.jl:128
 in (::PyAMG.#kw##solve)(::Array{Any,1}, ::PyAMG.#solve, ::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /home/vagrant/.julia/v0.5/PyAMG/test/runtests.jl, in expression starting on line 188
================================[ ERROR: PyAMG ]================================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.5/PyAMG/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: Removing DataStructures v0.5.3
INFO: Removing IterativeSolvers v0.3.1
INFO: Removing LinearMaps v0.3.0
INFO: Removing RecipesBase v0.1.0
INFO: Removing SpecialFunctions v0.1.1
INFO: Removing StatsBase v0.16.0
INFO: Removing SugarBLAS v0.0.3
INFO: Removing UnicodePlots v0.2.4
ERROR: PyAMG had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at ./pkg/entry.jl:748
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at ./<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./pkg/dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at ./<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in test(::String, ::Vararg{String,N}) at ./pkg/pkg.jl:258
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321

>>> End of log
