>>> 'Pkg.add("RobotOS")' log
INFO: Installing PyCall v0.7.3
INFO: Installing RobotOS v0.2.0
INFO: Package database updated

>>> 'using RobotOS' log
Julia Version 0.4.0-dev+2656
Commit a9f526e (2015-01-13 03:42 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

>>> test log

ERROR: python import error: No module named 'geometry_msgs'
 in error at error.jl:19
 in importtype at /home/idunning/pkgtest/.julia/v0.4/RobotOS/src/gentypes.jl:114
 in _usepkg at /home/idunning/pkgtest/.julia/v0.4/RobotOS/src/gentypes.jl:77
 in include at ./boot.jl:248
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:248
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:312
 in _start at ./client.jl:396
while loading /home/idunning/pkgtest/.julia/v0.4/RobotOS/test/test_types.jl, in expression starting on line 3
while loading /home/idunning/pkgtest/.julia/v0.4/RobotOS/test/runtests.jl, in expression starting on line 5
INFO: Testing RobotOS
===============================[ ERROR: RobotOS ]===============================

failed process: Process(`/home/idunning/julia04/usr/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/idunning/pkgtest/.julia/v0.4/RobotOS/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: RobotOS had test errors
 in error at error.jl:19
 in test at pkg/entry.jl:717
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:68
 in process_options at ./client.jl:234
 in _start at ./client.jl:396


>>> end of log
